# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(336, 327)
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(10, 30, 113, 22))
        self.name.setObjectName("name")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 131, 16))
        self.label_2.setObjectName("label_2")
        self.roast = QtWidgets.QLineEdit(Form)
        self.roast.setGeometry(QtCore.QRect(10, 80, 113, 22))
        self.roast.setObjectName("roast")
        self.group = QtWidgets.QComboBox(Form)
        self.group.setGeometry(QtCore.QRect(10, 120, 121, 21))
        self.group.setObjectName("group")
        self.group.addItem("")
        self.group.addItem("")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 160, 131, 16))
        self.label_3.setObjectName("label_3")
        self.desc = QtWidgets.QPlainTextEdit(Form)
        self.desc.setGeometry(QtCore.QRect(10, 180, 311, 51))
        self.desc.setObjectName("desc")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 240, 55, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(10, 270, 55, 16))
        self.label_5.setObjectName("label_5")
        self.price = QtWidgets.QSpinBox(Form)
        self.price.setGeometry(QtCore.QRect(70, 240, 61, 22))
        self.price.setMaximum(999999999)
        self.price.setObjectName("price")
        self.volume = QtWidgets.QSpinBox(Form)
        self.volume.setGeometry(QtCore.QRect(70, 270, 61, 22))
        self.volume.setMaximum(999999999)
        self.volume.setObjectName("volume")
        self.okbutton = QtWidgets.QPushButton(Form)
        self.okbutton.setGeometry(QtCore.QRect(210, 290, 93, 28))
        self.okbutton.setObjectName("okbutton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Название"))
        self.label_2.setText(_translate("Form", "Степень обжарки"))
        self.group.setItemText(0, _translate("Form", "Молотый"))
        self.group.setItemText(1, _translate("Form", "В зёрнах"))
        self.label_3.setText(_translate("Form", "Описание"))
        self.label_4.setText(_translate("Form", "Цена"))
        self.label_5.setText(_translate("Form", "Объём"))
        self.okbutton.setText(_translate("Form", "OK"))
